typography_spectrum: 0.4481376097537577
color:
  brandColors:
    - '#000000'
    - '#b0b7d1'
    - '#613a3d'
    - '#ce7663'
    - '#6490c2'
  brandStrength: 0.0625
  lightness: 0.75
  saturation: 0.125
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6869421657174826
analytics:
  google: null
  facebook: null
  twitter: null
name: Bohuslav Rattay
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Bohuslav Rattay
description: Conductor
purpose: []
