name: Bohuslav Rattay
favicon: null
layout_spectrum: 0.6869421657174826
typography_spectrum: 0.4481376097537577
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.06981270527467132
  lightness: 0.7788426228798926
  saturation: 0.4883869541808963
  rhythmicContrast: 0.5759011821355671
purpose: []
