title: Bohuslav Rattay
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: Conductor
color:
  saturation: 0.125
  brandStrength: 0.4910394
  lightness: 0.75
  brandColors:
    - '#0057F4'
    - '#0C0B1D'
    - '#C04F2F'
    - '#FFD595'
    - '#D8985B'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
name: Bohuslav Rattay
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4481376097537577
layout_spectrum: 0.1594982
